<?php
// Doctor profile + review system, retained from the production plugin.
function dr_create_review_table(){global $wpdb;$table=$wpdb->prefix.'dr_reviews';$charset=$wpdb->get_charset_collate();$sql="CREATE TABLE IF NOT EXISTS $table (id bigint(20) NOT NULL AUTO_INCREMENT,doctor_id bigint(20) NOT NULL,reviewer_name varchar(100) NOT NULL,rating tinyint(1) NOT NULL DEFAULT 5,review_text text NOT NULL,created_at datetime DEFAULT NULL,status varchar(20) DEFAULT 'pending',PRIMARY KEY (id),KEY doctor_id (doctor_id),KEY status (status)) $charset;";require_once ABSPATH.'wp-admin/includes/upgrade.php';dbDelta($sql);}

add_action('wp_ajax_dr_submit_review','dr_submit_review_handler');add_action('wp_ajax_nopriv_dr_submit_review','dr_submit_review_handler');
function dr_submit_review_handler(){
 if(!isset($_POST['nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nonce'])),'dr_review_nonce'))wp_send_json_error('Invalid request');
 $doctor_id=isset($_POST['doctor_id'])?absint($_POST['doctor_id']):0;
 $name=isset($_POST['reviewer_name'])?sanitize_text_field(wp_unslash($_POST['reviewer_name'])):'';
 $rating=isset($_POST['rating'])?absint($_POST['rating']):0;
 $text=isset($_POST['review_text'])?sanitize_textarea_field(wp_unslash($_POST['review_text'])):'';
 if('doctor'!==get_post_type($doctor_id)||'publish'!==get_post_status($doctor_id)||!$name||!$text||$rating<1||$rating>5||strlen($name)>100||strlen($text)>3000)wp_send_json_error('সব তথ্য সঠিকভাবে পূরণ করুন');
 $ip=isset($_SERVER['REMOTE_ADDR'])?sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'])):'unknown';
 $rate='dr_review_'.hash('sha256',$ip.'|'.$doctor_id);
 if(get_transient($rate))wp_send_json_error('অনুগ্রহ করে কিছুক্ষণ পরে আবার চেষ্টা করুন।');
 global $wpdb;
 $ok=$wpdb->insert($wpdb->prefix.'dr_reviews',array('doctor_id'=>$doctor_id,'reviewer_name'=>$name,'rating'=>$rating,'review_text'=>$text,'created_at'=>current_time('mysql'),'status'=>'pending'),array('%d','%s','%d','%s','%s','%s'));
 if(false===$ok)wp_send_json_error('রিভিউ সংরক্ষণ করা যায়নি।');
 set_transient($rate,1,10*MINUTE_IN_SECONDS);
 wp_send_json_success('রিভিউ জমা হয়েছে এবং অনুমোদনের অপেক্ষায় আছে।');
}
function dr_render_profile_page($pid){global $wpdb;$table=$wpdb->prefix.'dr_reviews';$reviews=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table WHERE doctor_id=%d AND status='approved' ORDER BY created_at DESC",$pid));$count=count($reviews);$avg=$count?round(array_sum(array_column($reviews,'rating'))/$count,1):0;$fields=array('designation'=>get_post_meta($pid,'designation',true),'workplace'=>get_post_meta($pid,'workplace',true),'clinic'=>get_post_meta($pid,'clinic',true),'phone'=>get_post_meta($pid,'phone',true),'address'=>get_post_meta($pid,'address',true),'map_link'=>get_post_meta($pid,'map_link',true),'facebook_link'=>get_post_meta($pid,'facebook_link',true),'division'=>get_post_meta($pid,'division',true),'district'=>get_post_meta($pid,'district',true),'upazila'=>get_post_meta($pid,'upazila',true),'experience'=>get_post_meta($pid,'experience',true),'vbac_support'=>get_post_meta($pid,'vbac_support',true));ob_start();?>
<style>.dr-profile-wrap{font-family:'Segoe UI',sans-serif;max-width:900px;margin:0 auto;color:#333}.dr-profile-card,.dr-review-item,.dr-review-form{background:#fff;border:1px solid #d1e8e4;border-radius:14px;padding:22px;margin-bottom:18px}.dr-profile-head{display:flex;gap:22px;align-items:center}.dr-profile-head img,.dr-profile-icon{width:120px;height:120px;border-radius:50%;object-fit:cover}.dr-profile-icon{display:flex;align-items:center;justify-content:center;background:#f0f7f6;font-size:50px}.dr-profile-wrap h1,.dr-profile-wrap h2{color:#418681}.dr-profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.dr-profile-grid div{background:#f7faf9;padding:10px;border-radius:8px}.dr-stars{color:#f5a623}.dr-review-form input,.dr-review-form textarea,.dr-review-form select{width:100%;box-sizing:border-box;padding:10px;margin:5px 0 12px;border:1px solid #ccc;border-radius:7px}.dr-review-form button{width:100%;padding:11px;background:#418681;color:#fff;border:0;border-radius:8px;font-weight:bold;cursor:pointer}@media(max-width:600px){.dr-profile-head{align-items:flex-start;flex-direction:column}.dr-profile-grid{grid-template-columns:1fr}}</style>
<div class="dr-profile-wrap"><a href="<?php echo esc_url(dr_get_doctor_back_url_v37());?>">← সকল ডাক্তার দেখুন</a><div class="dr-profile-card"><div class="dr-profile-head"><div><?php echo has_post_thumbnail($pid)?get_the_post_thumbnail($pid,'medium'):'<div class="dr-profile-icon">👨‍⚕️</div>';?></div><div><h1><?php echo esc_html(get_the_title($pid));?></h1><strong><?php echo esc_html($fields['designation']);?></strong><?php if($count):?><p><span class="dr-stars">★★★★★</span> <?php echo esc_html($avg);?> / 5 (<?php echo intval($count);?>)</p><?php endif;?><?php if($fields['experience']):?><p>🩺 অভিজ্ঞতা: <?php echo esc_html($fields['experience']);?> বছর</p><?php endif;?><?php if($fields['vbac_support']):?><p><strong>VBAC Support</strong></p><?php endif;?></div></div><div class="dr-profile-grid"><?php foreach(array('workplace'=>'🏥 হাসপাতাল','clinic'=>'🩺 চেম্বার','phone'=>'📞 ফোন','division'=>'🗺️ বিভাগ','district'=>'🏙️ জেলা','upazila'=>'📍 উপজেলা','address'=>'🏠 ঠিকানা') as $k=>$label)if($fields[$k])echo '<div><strong>'.esc_html($label).'</strong><br>'.esc_html($fields[$k]).'</div>';?></div><?php if($fields['map_link']):?><p><a target="_blank" rel="noopener" href="<?php echo esc_url($fields['map_link']);?>">📌 Google Maps</a></p><?php endif;?><?php if($fields['facebook_link']):?><p><a target="_blank" rel="noopener" href="<?php echo esc_url($fields['facebook_link']);?>">📘 Facebook Profile</a></p><?php endif;?></div>
<h2>💬 রোগীদের রিভিউ <?php if($count)echo '<small>('.intval($count).'টি)</small>';?></h2><?php if(!$reviews):?><p>এখনো কোনো রিভিউ নেই। প্রথম রিভিউ লিখুন!</p><?php else:foreach($reviews as $r):?><div class="dr-review-item"><strong>👤 <?php echo esc_html($r->reviewer_name);?></strong> <span class="dr-stars"><?php for($i=1;$i<=5;$i++)echo $i<=$r->rating?'★':'☆';?></span><small><?php echo esc_html(date('d M Y',strtotime($r->created_at)));?></small><p><?php echo esc_html($r->review_text);?></p></div><?php endforeach;endif;?>
<div class="dr-review-form"><h3>✍️ আপনার রিভিউ লিখুন</h3><div id="dr-review-msg"></div><label>আপনার নাম *</label><input id="dr-rev-name" maxlength="100"><label>রেটিং *</label><select id="dr-rev-rating"><option value="5">5</option><option value="4">4</option><option value="3" selected>3</option><option value="2">2</option><option value="1">1</option></select><label>রিভিউ *</label><textarea id="dr-rev-text"></textarea><button id="dr-submit-review">রিভিউ জমা দিন</button></div></div>
<script>document.getElementById('dr-submit-review').addEventListener('click',function(){var b=this,n=document.getElementById('dr-rev-name').value.trim(),t=document.getElementById('dr-rev-text').value.trim(),r=document.getElementById('dr-rev-rating').value,m=document.getElementById('dr-review-msg');if(!n||!t){m.textContent='সব তথ্য পূরণ করুন।';return}b.disabled=true;var fd=new FormData();fd.append('action','dr_submit_review');fd.append('nonce','<?php echo wp_create_nonce('dr_review_nonce');?>');fd.append('doctor_id','<?php echo intval($pid);?>');fd.append('reviewer_name',n);fd.append('rating',r);fd.append('review_text',t);fetch('<?php echo admin_url('admin-ajax.php');?>',{method:'POST',body:fd}).then(x=>x.json()).then(d=>{if(d.success){m.textContent='রিভিউ সফলভাবে যোগ হয়েছে!';setTimeout(()=>location.reload(),900)}else{m.textContent=d.data||'কিছু একটা সমস্যা হয়েছে।';b.disabled=false}}).catch(()=>{m.textContent='সংযোগ সমস্যা।';b.disabled=false})});</script><?php return ob_get_clean();}
add_action('admin_menu',function(){add_submenu_page('edit.php?post_type=doctor','Reviews','Reviews','manage_options','dr-reviews','dr_reviews_admin_page');});
function dr_reviews_admin_page(){
 if(!current_user_can('manage_options'))wp_die(esc_html__('Forbidden','bangladesh-doctor-finder'));
 global $wpdb;$table=$wpdb->prefix.'dr_reviews';
 if(isset($_GET['delete_review'])){ $id=absint($_GET['delete_review']); check_admin_referer('dr_delete_review_'.$id); $wpdb->delete($table,array('id'=>$id),array('%d')); }
 if(isset($_GET['approve_review'])){ $id=absint($_GET['approve_review']); check_admin_referer('dr_approve_review_'.$id); $wpdb->update($table,array('status'=>'approved'),array('id'=>$id),array('%s'),array('%d')); }
 $reviews=$wpdb->get_results("SELECT r.*,p.post_title AS doctor_name FROM {$table} r LEFT JOIN {$wpdb->posts} p ON r.doctor_id=p.ID ORDER BY r.created_at DESC LIMIT 100");?>
 <div class="wrap"><h1>Doctor Reviews</h1><table class="widefat striped"><thead><tr><th>ডাক্তার</th><th>রিভিউকারী</th><th>রেটিং</th><th>রিভিউ</th><th>তারিখ</th><th>Status</th><th>Action</th></tr></thead><tbody>
 <?php if($reviews):foreach($reviews as $rv): $approve=wp_nonce_url(admin_url('edit.php?post_type=doctor&page=dr-reviews&approve_review='.absint($rv->id)),'dr_approve_review_'.absint($rv->id)); $delete=wp_nonce_url(admin_url('edit.php?post_type=doctor&page=dr-reviews&delete_review='.absint($rv->id)),'dr_delete_review_'.absint($rv->id));?>
 <tr><td><?php echo esc_html($rv->doctor_name);?></td><td><?php echo esc_html($rv->reviewer_name);?></td><td><?php echo absint($rv->rating);?>/5</td><td><?php echo esc_html(wp_trim_words($rv->review_text,15));?></td><td><?php echo esc_html(date_i18n('d/m/Y',strtotime($rv->created_at)));?></td><td><?php echo esc_html($rv->status);?></td><td><?php if('approved'!==$rv->status):?><a href="<?php echo esc_url($approve);?>">Approve</a> | <?php endif;?><a href="<?php echo esc_url($delete);?>" onclick="return confirm('মুছে ফেলবেন?')">Delete</a></td></tr>
 <?php endforeach;else:?><tr><td colspan="7">কোনো রিভিউ নেই।</td></tr><?php endif;?></tbody></table></div><?php
}
