<?php
function dr_translate_bn_to_en($q) {
    $map = array('ঢাকা'=>'Dhaka','গাজীপুর'=>'Gazipur','চট্টগ্রাম'=>'Chattogram','চিটাগাং'=>'Chattogram','কক্সবাজার'=>"Cox's Bazar",'রাজশাহী'=>'Rajshahi','ধানমন্ডি'=>'Dhanmondi','গুলশান'=>'Gulshan','মিরপুর'=>'Mirpur','মোহাম্মদপুর'=>'Mohammadpur','উত্তরা'=>'Uttara','গাজীপুর সদর'=>'Gazipur Sadar','শ্রীপুর'=>'Sreepur','হাটহাজারী'=>'Hathazari','পটিয়া'=>'Patiya','সীতাকুণ্ড'=>'Sitakunda','রামু'=>'Ramu','টেকনাফ'=>'Teknaf','পবা'=>'Paba','পুঠিয়া'=>'Puthia');
    $q_lower = mb_strtolower(trim($q)); foreach ($map as $bn=>$en) if (mb_strtolower($bn)===$q_lower || mb_stripos($q,$bn)!==false) return $en; return $q;
}
function dr_get_location_suggestions_v37($q='') {
    $db=get_bd_hardcoded_database_full(); $q=trim(dr_translate_bn_to_en($q)); $out=array(); if(strlen($q)<2)return $out;
    foreach($db as $div=>$districts){ if(stripos($div,$q)!==false)$out[]=array('value'=>$div,'type'=>'বিভাগ','div'=>$div,'dist'=>'','upz'=>''); foreach($districts as $dist=>$upazilas){ if(stripos($dist,$q)!==false)$out[]=array('value'=>$dist,'type'=>'জেলা','div'=>$div,'dist'=>$dist,'upz'=>''); foreach($upazilas as $upz)if(stripos($upz,$q)!==false)$out[]=array('value'=>$upz,'type'=>'উপজেলা/এলাকা','div'=>$div,'dist'=>$dist,'upz'=>$upz); }} return array_slice($out,0,12);
}
add_action('wp_ajax_dr_location_suggest_v37','dr_location_suggest_v37_handler'); add_action('wp_ajax_nopriv_dr_location_suggest_v37','dr_location_suggest_v37_handler');
function dr_location_suggest_v37_handler(){ wp_send_json(dr_get_location_suggestions_v37(sanitize_text_field($_POST['q']??''))); }
function dr_find_location_context_v37($q='',$div='',$dist='',$upz='') {
    $db=get_bd_hardcoded_database_full(); if($dist)return array('div'=>$div,'dist'=>$dist,'upz'=>$upz); $terms=array_unique(array_filter(array($q,dr_translate_bn_to_en($q))));
    foreach($terms as $term){$term=trim($term);if($term==='')continue;foreach($db as $d=>$districts){if(strcasecmp($d,$term)===0||stripos($d,$term)!==false)return array('div'=>$d,'dist'=>'','upz'=>'');foreach($districts as $ds=>$upazilas){if(strcasecmp($ds,$term)===0||stripos($ds,$term)!==false)return array('div'=>$d,'dist'=>$ds,'upz'=>'');foreach($upazilas as $u)if(strcasecmp($u,$term)===0||stripos($u,$term)!==false)return array('div'=>$d,'dist'=>$ds,'upz'=>$u);}}} return array('div'=>$div,'dist'=>$dist,'upz'=>$upz);
}
function dr_district_centers_v37(){return array('Dhaka'=>array(23.8103,90.4125),'Gazipur'=>array(24.0023,90.4264),'Chattogram'=>array(22.3569,91.7832),"Cox's Bazar"=>array(21.4272,92.0058),'Rajshahi'=>array(24.3745,88.6042));}
function dr_distance_km_v37($a,$b){$r=6371;$lat1=deg2rad($a[0]);$lon1=deg2rad($a[1]);$lat2=deg2rad($b[0]);$lon2=deg2rad($b[1]);$dlat=$lat2-$lat1;$dlon=$lon2-$lon1;$h=sin($dlat/2)*sin($dlat/2)+cos($lat1)*cos($lat2)*sin($dlon/2)*sin($dlon/2);return 2*$r*asin(min(1,sqrt($h)));}
function dr_get_doctors_by_meta_v37($key,$value){if(!$value)return array();$q=new WP_Query(array('post_type'=>'doctor','posts_per_page'=>-1,'meta_query'=>array(array('key'=>$key,'value'=>$value,'compare'=>'='))));$posts=array();if($q->have_posts()){while($q->have_posts()){$q->the_post();$posts[get_the_ID()]=get_post(get_the_ID());}wp_reset_postdata();}return $posts;}
function dr_smart_fallback_posts_v37($ctx){if(!empty($ctx['upz'])&&!empty($ctx['dist'])){$posts=dr_get_doctors_by_meta_v37('district',$ctx['dist']);if($posts)return array($posts,$ctx['dist']);}if(!empty($ctx['dist'])){$centers=dr_district_centers_v37();if(isset($centers[$ctx['dist']])){$distances=array();foreach($centers as $d=>$c)if($d!==$ctx['dist'])$distances[$d]=dr_distance_km_v37($centers[$ctx['dist']],$c);asort($distances);foreach($distances as $near=>$km){$posts=dr_get_doctors_by_meta_v37('district',$near);if($posts)return array($posts,$near);}}}if(!empty($ctx['div'])){$posts=dr_get_doctors_by_meta_v37('division',$ctx['div']);if($posts)return array($posts,$ctx['div']);}return array(array(),'');}
function dr_get_profile_url_v37($pid){$url=get_permalink(intval($pid));return $url?$url:home_url('/');}
function dr_get_doctor_back_url_v37(){$ref=wp_get_referer();if($ref)return remove_query_arg(array('doctor_id','_wpnonce'),$ref);$archive=get_post_type_archive_link('doctor');return $archive?$archive:home_url('/');}
add_filter('the_content','dr_single_doctor_content_v37',20);
function dr_single_doctor_content_v37($content){if(is_admin()||!is_singular('doctor')||!in_the_loop()||!is_main_query())return $content;return dr_render_profile_page(get_the_ID());}
function dr_render_doctor_cards_v37($all_posts,$nearby_mode=false,$nearby_area='',$q=''){
 if(!empty($all_posts)){if($nearby_mode&&$nearby_area)echo '<div class="nearby-notice">⚠️ <strong>'.esc_html($q?:'নির্বাচিত এলাকা').'</strong> এলাকায় সরাসরি কোনো ডাক্তার পাওয়া যায়নি। নিকটবর্তী <strong>'.esc_html($nearby_area).'</strong> এলাকার ডাক্তার দেখানো হচ্ছে।</div>';foreach($all_posts as $pid=>$post){setup_postdata($post);$score=(int)get_post_meta($pid,'dr_votes',true);$experience=get_post_meta($pid,'experience',true);?>
 <div class="dr-card"><div class="dr-avatar"><?php echo has_post_thumbnail($pid)?get_the_post_thumbnail($pid,'thumbnail'):'<div class="dr-avatar-icon">👨‍⚕️</div>';?></div><div class="dr-info"><h2><a href="<?php echo esc_url(dr_get_profile_url_v37($pid));?>" style="color:#418681;text-decoration:none;"><?php echo esc_html(get_the_title($pid));?></a><?php if(get_post_meta($pid,'vbac_support',true)):?> <span class="vbac-badge">VBAC Support</span><?php endif;?></h2><p style="margin:2px 0;"><strong><?php echo esc_html(get_post_meta($pid,'designation',true));?></strong></p><?php if($experience):?><span class="exp-badge">🩺 অভিজ্ঞতা: <?php echo esc_html($experience);?> বছর</span><?php endif;?><div class="meta-grid"><span>🏥 <strong>হাসপাতাল:</strong> <?php echo esc_html(get_post_meta($pid,'workplace',true));?></span><span>🩺 <strong>চেম্বার:</strong> <?php echo esc_html(get_post_meta($pid,'clinic',true));?></span><span>🗺️ <strong>বিভাগ:</strong> <?php echo esc_html(get_post_meta($pid,'division',true));?></span><span>🏙️ <strong>জেলা:</strong> <?php echo esc_html(get_post_meta($pid,'district',true));?></span><span>📍 <strong>উপজেলা:</strong> <?php echo esc_html(get_post_meta($pid,'upazila',true));?></span><span>📞 <strong>ফোন:</strong> <?php echo esc_html(get_post_meta($pid,'phone',true));?></span><?php if($addr=get_post_meta($pid,'address',true)):?><div style="grid-column:span 2;">🏠 <strong>বিস্তারিত ঠিকানা:</strong> <?php echo esc_html($addr);?></div><?php endif;?><?php if($map=get_post_meta($pid,'map_link',true)):?><div style="grid-column:span 2;">📌 <a href="<?php echo esc_url($map);?>" target="_blank" style="color:#418681;text-decoration:none;font-weight:bold;">Google Maps এ দেখুন ➔</a></div><?php endif;?><?php if($fb=get_post_meta($pid,'facebook_link',true)):?><div style="grid-column:span 2;">📘 <a href="<?php echo esc_url($fb);?>" target="_blank" style="color:#3b5998;text-decoration:none;font-weight:bold;">Facebook Profile ➔</a></div><?php endif;?></div></div><div class="vote-panel"><div class="v-score"><?php echo $score;?></div><small>জন রেকমেন্ড করেছেন</small><div class="v-btn-group" style="display:flex;flex-direction:column;gap:5px;margin-top:10px;"><button class="vote-act-btn" data-id="<?php echo $pid;?>" data-type="up" style="background:#418681;color:#fff;border:none;padding:8px;border-radius:20px;cursor:pointer;font-weight:bold;">রেকমেন্ড 👍</button><button class="vote-act-btn" data-id="<?php echo $pid;?>" data-type="down" style="background:#ffeded;color:#d9534f;border:none;padding:8px;border-radius:20px;cursor:pointer;font-weight:bold;">নট রেকমেন্ড 👎</button></div></div></div><?php }wp_reset_postdata();}else echo "<p style='text-align:center;color:#888;padding:30px 0;'>কোনো ডাক্তার পাওয়া যায়নি।</p>";
}
add_action('wp_ajax_master_ajax_v37','master_ajax_v37_handler');add_action('wp_ajax_nopriv_master_ajax_v37','master_ajax_v37_handler');
function master_ajax_v37_handler(){$q=sanitize_text_field($_POST['q']??'');$div=sanitize_text_field($_POST['div']??'');$dist=sanitize_text_field($_POST['dist']??'');$upz=sanitize_text_field($_POST['upz']??'');$all_posts=array();$nearby_mode=false;$nearby_area='';$dropdown_mq=array('relation'=>'AND');if($div)$dropdown_mq[]=array('key'=>'division','value'=>$div,'compare'=>'=');if($dist)$dropdown_mq[]=array('key'=>'district','value'=>$dist,'compare'=>'=');if($upz)$dropdown_mq[]=array('key'=>'upazila','value'=>$upz,'compare'=>'=');$has_dropdown=count($dropdown_mq)>1;if($q!==''){$terms=array_unique(array_filter(array($q,dr_translate_bn_to_en($q))));foreach($terms as $term){$args=array('post_type'=>'doctor','posts_per_page'=>-1,'s'=>$term);if($has_dropdown)$args['meta_query']=$dropdown_mq;$tq=new WP_Query($args);if($tq->have_posts()){while($tq->have_posts()){$tq->the_post();$all_posts[get_the_ID()]=get_post(get_the_ID());}wp_reset_postdata();}$meta_or=array('relation'=>'OR');foreach(array('division','district','upazila','workplace','clinic','address','designation','phone')as$field)$meta_or[]=array('key'=>$field,'value'=>$term,'compare'=>'LIKE');$mq=$has_dropdown?array('relation'=>'AND',$dropdown_mq,$meta_or):$meta_or;$mq2=new WP_Query(array('post_type'=>'doctor','posts_per_page'=>-1,'meta_query'=>$mq));if($mq2->have_posts()){while($mq2->have_posts()){$mq2->the_post();$all_posts[get_the_ID()]=get_post(get_the_ID());}wp_reset_postdata();}}}else{$args=array('post_type'=>'doctor','posts_per_page'=>-1);if($has_dropdown)$args['meta_query']=$dropdown_mq;$query=new WP_Query($args);if($query->have_posts()){while($query->have_posts()){$query->the_post();$all_posts[get_the_ID()]=get_post(get_the_ID());}wp_reset_postdata();}}if(empty($all_posts)){$ctx=dr_find_location_context_v37($q,$div,$dist,$upz);list($fallback_posts,$fallback_area)=dr_smart_fallback_posts_v37($ctx);if($fallback_posts){$all_posts=$fallback_posts;$nearby_mode=true;$nearby_area=$fallback_area;}}dr_render_doctor_cards_v37($all_posts,$nearby_mode,$nearby_area,$q?:trim($upz?:$dist?:$div));wp_die();}
